修复一点东西
project-mirai/mirai-plugin-center pull request #14
Opened 2021-04-18 17:47 UTC by HoshinoTented

2021-04-18 17:47 UTC, HoshinoTented commented
经过一点测试

2021-04-18 17:57 UTC, HoshinoTented commented
@Him188 @mzdluo123

2021-04-19 00:28 UTC, Him188 approved these changes

2021-04-19 02:43 UTC, mzdluo123 approved these changes

2021-04-19 03:43 UTC, Karlatemp requested changes

2021-04-19 03:43 UTC, Karlatemp commented on server/src/controller/MavenRepositoryUploadController.kt
> +        private fun String.doSplitPath(): PublishArtifact {
Delete

2021-04-19 03:45 UTC, Karlatemp commented on server/test/MavenRepositoryUploadControllerTests.kt
> +        val path = Path.of("v1", "publish", "upload", "net", "mamoe", "mirai", "mirai-core", "1.1.4", "mirai-core-1.1.4-all.jar")
Test also
```
/v1/publish/upload/
/v1/publish/upload/net
/v1/publish/upload/net/mamoe
/v1/publish/upload/net/mamoe/mirai
/v1/publish/upload/net/mamoe/mirai/mirai-core
....
```

2021-04-19 05:22 UTC, Karlatemp approved these changes

2021-04-19 06:03 UTC, mzdluo123 commented
commit信息夹带私货，差评

2021-04-19 06:09 UTC, HoshinoTented commented
> commit信息夹带私货，差评

？

2021-04-19 09:31 UTC, merged