Add file-based PluginsManager
project-mirai/mirai-plugin-center pull request #4
Opened 2021-04-08 07:49 UTC by HoshinoTented

2021-04-08 07:49 UTC, HoshinoTented commented
plz review my code and give me some adivces

2021-04-08 08:32 UTC, HoshinoTented commented
@Him188

2021-04-08 11:27 UTC, Him188 commented on server/src/manager/PluginsManager.kt
> +        uploadFromStream(`in`.inputStream)
没有 close stream?

2021-04-08 11:27 UTC, Him188 commented on server/src/manager/PluginsManager.kt
> +            if (! file.parentFile.mkdirs()) {
如果 parentFile 存在, `mkdirs` 就会返回 false

2021-04-08 11:27 UTC, Him188 commented on server/src/manager/PluginsManager.kt
> +        TODO()
```suggestion
        dir.deleteRecursively()
```

2021-04-08 20:15 UTC, HoshinoTented commented on server/src/manager/PluginsManager.kt
> +        uploadFromStream(`in`.inputStream)
我以为 transferTo 会 close，我 sabee 了

2021-04-09 03:42 UTC, Him188 commented on server/src/manager/PluginsManager.kt
> +        uploadFromStream(`in`.inputStream)
一般的操作都不会 close，要stream 的创建者去 close

2021-04-09 03:43 UTC, Him188 requested changes

2021-04-09 03:43 UTC, Him188 commented on server/src/manager/PluginsManager.kt
> +        `in`.use {
应该由调用方（stream 创建方）close

2021-04-09 07:59 UTC, HoshinoTented commented on server/src/manager/PluginsManager.kt
> +        `in`.use {
:(

2021-04-09 08:00 UTC, HoshinoTented commented on server/src/manager/PluginsManager.kt
> +        `in`.use {
但后续版本我想直接用 MultipartFile::trransferTo

2021-04-09 08:00 UTC, HoshinoTented commented on server/src/manager/PluginsManager.kt
> +        `in`.use {
我不知道它会不会 close

2021-04-09 08:06 UTC, HoshinoTented commented on server/src/manager/PluginsManager.kt
> +        `in`.use {
看起来不会，那我要约定 upload 会关闭 MultipartFile 的 InputStream 吗

2021-04-09 08:55 UTC, Him188 commented on server/src/manager/PluginsManager.kt
> +        `in`.use {
不约定, 由调用方关闭即可

2021-04-09 09:18 UTC, HoshinoTented commented on server/src/manager/PluginsManager.kt
> +        `in`.use {
hao

2021-04-09 15:52 UTC, closed without merging